SELECT
        DISTINCT (CUST_ACCT.A_NO),
        CUST_BILL.SKU,
        CUST_BILL.VOLUME,
        CUST_BILL.DESCRIPTION
FROM

(SELECT 
        HCA.ACCOUNT_NUMBER          CUST_ACCT_NO,
        HCA.ACCOUNT_NAME            CUST_ACCT_NAME,
        HCSUA.BILL_TO_SITE_USE_ID   CUST_BILL_ID
FROM 
        AR.HZ_CUST_ACCOUNTS         HCA,
        AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
        AR.HZ_CUST_SITE_USES_ALL   HCSUA
WHERE  
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
    AND HCSUA.BILL_TO_SITE_USE_ID IS NOT NULL)  CUST_DTLS,
(SELECT 
        --HCA.ACCOUNT_NUMBER          A_NO,
        HCSUA.BILL_TO_SITE_USE_ID   BILL_ID
FROM 
        AR.HZ_CUST_ACCOUNTS         HCA,
        AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
        AR.HZ_CUST_SITE_USES_ALL   HCSUA
WHERE  
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID)  CUST_ACCT,
 
(SELECT 
        MSIB.SEGMENT1               SKU,
        RCTLA.QUANTITY_INVOICED     VOLUME,
        RCTLA.DESCRIPTION           DESCRIPTION,
        --RCTA.BILL_TO_SITE_USE_ID    BILL_ID
FROM
        inv.mtl_system_items_b          MSIB,
        ar.ra_customer_trx_lines_all    RCTLA,
        AR.RA_CUSTOMER_TRX_ALL          RCTA
WHERE
        RCTLA.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
    AND RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID)   CUST_BILL
    
WHERE
        CUST_ACCT.BILL_ID = CUST_BILL.BILL_ID;