SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='Project001';

select *
from INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME='A1';

select * from Persons;