SELECT AB.REGION  REGION,
       AB.DEPO_NAME DEPO_NAME,
       AB.CUST_ACC_NO CUST_ACC_NO,
       AB.CUST_NAME CUST_NAME,
       AB.VOL_27    VOL_27,
       GH.VOL       VOL
FROM
(SELECT
CUST_DTLS.REGION        REGION,
CUST_DTLS.DEPO_NAME     DEPO_NAME,
CUST_DTLS.CUST_ACC_NO   CUST_ACC_NO,
CUST_DTLS.CUST_NAME     CUST_NAME,
SUM(VOL_DTLS.VOLUME)   VOL_27
FROM
(SELECT 
    SUBSTR(HAOU.ATTRIBUTE4,1,2) REGION, 
    SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)) DEPO_NAME,
    TO_NUMBER(RT.SEGMENT4)     TERR_CODE,
    HCA.ACCOUNT_NUMBER  CUST_ACC_NO,
    HCSUA.SITE_USE_ID    BILL_ID,
    HCA.ACCOUNT_NAME     CUST_NAME
FROM
AR.HZ_CUST_ACCOUNTS                    HCA,
         AR.HZ_CUST_ACCT_SITES_ALL     HCASA,
         AR.HZ_CUST_SITE_USES_ALL      HCSUA,
         HR.HR_ALL_ORGANIZATION_UNITS  HAOU,
         AR.RA_TERRITORIES             RT,
         AR.HZ_LOCATIONS               HL,
         AR.HZ_PARTY_SITES             HPS
WHERE
         HCA.CUST_ACCOUNT_ID=HCASA.CUST_ACCOUNT_ID
         AND  HCASA.CUST_ACCT_SITE_ID=HCSUA.CUST_ACCT_SITE_ID
         AND  HCSUA.WAREHOUSE_ID=HAOU.ORGANIZATION_ID
         AND  HCSUA.TERRITORY_ID=RT.TERRITORY_ID
         AND  HCASA.PARTY_SITE_ID=HPS.PARTY_SITE_ID
         AND  HPS.LOCATION_ID=HL.LOCATION_ID
         AND  HCSUA.SITE_USE_CODE='BILL_TO'
         AND  HAOU.ATTRIBUTE1='DEPOT'
         AND  ((SUBSTR(HAOU.ATTRIBUTE4,1,2) IN ('N2','C2'))
         OR   HL.STATE LIKE 'GOA')) CUST_DTLS,
(SELECT   RCTLA.INVENTORY_ITEM_ID         INV_ID, 
         RCTA.TRX_NUMBER                 TRX_NUMBER,
         RCTA.TRX_DATE                   TRX_DATE,
         RCTA.BILL_TO_SITE_USE_ID        BILL_ID,
         RCTLA.DESCRIPTION               DESCRIPTION1,
         MSIB.SEGMENT1             SKU,
          CASE
                    WHEN SUBSTR(RCTLA.DESCRIPTION,6,15) = 'MANUAL_DISCOUNT' THEN 0
                    ELSE
                      CASE
                        WHEN RCTTA.TYPE = 'CM' THEN MSIB.PACK_SIZE * NVL(RCTLA.QUANTITY_CREDITED,0)
                        ELSE MSIB.PACK_SIZE * NVL(RCTLA.QUANTITY_INVOICED,0)
                      END
                  END VOLUME
FROM
        AR.RA_CUSTOMER_TRX_LINES_ALL    RCTLA,
         AR.RA_CUSTOMER_TRX_ALL          RCTA,
         AR.RA_CUST_TRX_TYPES_ALL        RCTTA,
         (
            SELECT MSIB.INVENTORY_ITEM_ID
                  ,MSIB.SEGMENT1
                  ,MSIB.SECONDARY_UOM_CODE  
                  ,NVL(BPIL.BPIL_INVOICE_UOM (MSIB.INVENTORY_ITEM_ID,MSIB.SECONDARY_UOM_CODE),0) PACK_SIZE
                  ,MSIB.DESCRIPTION
              FROM INV.MTL_SYSTEM_ITEMS_B     MSIB
             WHERE MSIB.ORGANIZATION_ID =83
               AND MSIB.SEGMENT1 NOT LIKE '%BULK%'
               AND MSIB.INVENTORY_ITEM_STATUS_CODE = 'Active'
               AND SUBSTR(MSIB.SEGMENT1,1,6) IN ('F00049')
          ) MSIB
WHERE    RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID
         AND RCTA.CUST_TRX_TYPE_ID=RCTTA.CUST_TRX_TYPE_ID
         AND MSIB.INVENTORY_ITEM_ID=RCTLA.INVENTORY_ITEM_ID
         AND RCTLA.DESCRIPTION NOT LIKE '%B99%'
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'YYYYMM')) = 201404
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'DD')) <= 03
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'DD')) >=01
       AND (RCTTA.NAME LIKE '%_INVOICE'
        OR  RCTTA.NAME LIKE '%_CN') ) VOL_DTLS
WHERE CUST_DTLS.BILL_ID=VOL_DTLS.BILL_ID
GROUP BY
CUST_DTLS.REGION,
CUST_DTLS.DEPO_NAME,
CUST_DTLS.CUST_ACC_NO,
CUST_DTLS.CUST_NAME
ORDER BY 1,2,3,4) AB,
(SELECT
CUST_DTLS.REGION        REGION,
CUST_DTLS.DEPO_NAME     DEPO_NAME,
CUST_DTLS.CUST_ACC_NO   CUST_ACC_NO,
CUST_DTLS.CUST_NAME     CUST_NAME,
SUM(VOL_DTLS1.VOLUME)   VOL
FROM
(SELECT 
    SUBSTR(HAOU.ATTRIBUTE4,1,2) REGION, 
    SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)) DEPO_NAME,
    TO_NUMBER(RT.SEGMENT4)     TERR_CODE,
    HCA.ACCOUNT_NUMBER  CUST_ACC_NO,
    HCSUA.SITE_USE_ID    BILL_ID,
    HCA.ACCOUNT_NAME     CUST_NAME
FROM
AR.HZ_CUST_ACCOUNTS                    HCA,
         AR.HZ_CUST_ACCT_SITES_ALL     HCASA,
         AR.HZ_CUST_SITE_USES_ALL      HCSUA,
         HR.HR_ALL_ORGANIZATION_UNITS  HAOU,
         AR.RA_TERRITORIES             RT
WHERE
         HCA.CUST_ACCOUNT_ID=HCASA.CUST_ACCOUNT_ID
         AND  HCASA.CUST_ACCT_SITE_ID=HCSUA.CUST_ACCT_SITE_ID
         AND  HCSUA.WAREHOUSE_ID=HAOU.ORGANIZATION_ID
         AND  HCSUA.TERRITORY_ID=RT.TERRITORY_ID
         AND  HCSUA.SITE_USE_CODE='BILL_TO'
         AND  HAOU.ATTRIBUTE1='DEPOT') CUST_DTLS,
(SELECT   RCTLA.INVENTORY_ITEM_ID         INV_ID, 
         RCTA.TRX_NUMBER                 TRX_NUMBER,
         RCTA.TRX_DATE                   TRX_DATE,
         RCTA.BILL_TO_SITE_USE_ID        BILL_ID,
         RCTLA.DESCRIPTION               DESCRIPTION1,
         MSIB.SEGMENT1             SKU,
          CASE
                    WHEN SUBSTR(RCTLA.DESCRIPTION,6,15) = 'MANUAL_DISCOUNT' THEN 0
                    ELSE
                      CASE
                        WHEN RCTTA.TYPE = 'CM' THEN MSIB.PACK_SIZE * NVL(RCTLA.QUANTITY_CREDITED,0)
                        ELSE MSIB.PACK_SIZE * NVL(RCTLA.QUANTITY_INVOICED,0)
                      END
           END VOLUME
FROM
        AR.RA_CUSTOMER_TRX_LINES_ALL    RCTLA,
         AR.RA_CUSTOMER_TRX_ALL          RCTA,
         AR.RA_CUST_TRX_TYPES_ALL        RCTTA,
         (
            SELECT MSIB.INVENTORY_ITEM_ID
                  ,MSIB.SEGMENT1
                  ,MSIB.SECONDARY_UOM_CODE  
                  ,NVL(BPIL.BPIL_INVOICE_UOM (MSIB.INVENTORY_ITEM_ID,MSIB.SECONDARY_UOM_CODE),0) PACK_SIZE
                  ,MSIB.DESCRIPTION
              FROM INV.MTL_SYSTEM_ITEMS_B     MSIB
             WHERE MSIB.ORGANIZATION_ID =83
               AND MSIB.SEGMENT1 NOT LIKE '%BULK%'
               AND MSIB.INVENTORY_ITEM_STATUS_CODE = 'Active'
               AND SUBSTR(MSIB.SEGMENT1,1,6) IN ('F00049')
          ) MSIB
WHERE    RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID
         AND RCTA.CUST_TRX_TYPE_ID=RCTTA.CUST_TRX_TYPE_ID
         AND MSIB.INVENTORY_ITEM_ID=RCTLA.INVENTORY_ITEM_ID
         AND RCTLA.DESCRIPTION NOT LIKE '%B99%'
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'YYYYMM')) = 201404
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'DD')) <= 15
       AND TO_NUMBER(TO_CHAR(RCTA.TRX_DATE,'DD')) >=01
       AND (RCTTA.NAME LIKE '%_INVOICE'
        OR  RCTTA.NAME LIKE '%_CN') ) VOL_DTLS1
WHERE CUST_DTLS.BILL_ID=VOL_DTLS1.BILL_ID
GROUP BY
CUST_DTLS.REGION,
CUST_DTLS.DEPO_NAME,
CUST_DTLS.CUST_ACC_NO,
CUST_DTLS.CUST_NAME
ORDER BY 1,2,3,4) GH  
WHERE AB.REGION=GH.REGION
      AND AB.DEPO_NAME=GH.DEPO_NAME
      AND AB.CUST_ACC_NO=GH.CUST_ACC_NO
      AND AB.CUST_NAME=GH.CUST_NAME;
   
