SELECT RT.SEGMENT2              REGN,
       RT.SEGMENT3              DEPO_CODE,
       HOUV.NAME                DEPO_NAME,
       TO_NUMBER(RT.SEGMENT4)   TERR_CODE,
       RSA.NAME                 TERR_NAME,   
       HCA.ACCOUNT_NUMBER       HCA_ACCOUNT_NUMBER, 
       HCA.CUST_ACCOUNT_ID,
       HCA.ACCOUNT_NAME         HCA_ACCOUNT_NAME,
       HCSUA.SITE_USE_CODE      SHIP_TO_SITE_USE_CODE, 
       HCSUA.SITE_USE_ID ,
       HCASA.CUST_ACCT_SITE_ID  SHIP_TO_CODE,
       BILL_TO.SITE_USE_CODE    BILL_TO_SITE_USE_CODE,
       HCSUA.BILL_TO_SITE_USE_ID,
       BILL_TO.CODE  BILL_TO_CODE,
       HCSUA.PRIMARY_FLAG,
       HPS.PARTY_SITE_NAME,
       HCSUA.ATTRIBUTE23  SITE_NAME,
       HL.ADDRESS1,
       HL.ADDRESS2,
       HL.ADDRESS3,
       HL.ADDRESS4, 
       HL.CITY, 
       HL.POSTAL_CODE, 
       HL.STATE, 
       HCA.SALES_CHANNEL_CODE   SBL_TYPE,
       HCASA.GLOBAL_ATTRIBUTE10 CUST_TYPE,
       HCASA.GLOBAL_ATTRIBUTE13 BIRTH_DATE,
       HCASA.GLOBAL_ATTRIBUTE1  LEGACY_CODE,
       TO_CHAR(HCASA.CREATION_DATE,'DD/MM/YYYY')  CREATION_DATE,
       HCPA.OVERALL_CREDIT_LIMIT                  CREDIT_LIMIT,
       NVL(CODE_42.CODE_42_PERCENTAGE,0)          CODE_42_PERCENTAGE,
       NVL(HCASA.GLOBAL_ATTRIBUTE19,'OTH')        GLOBAL_ATTRIBUTE19,
       FLV.MEANING                                CUST_TYPE_DESC
FROM   RA_TERRITORIES           RT,   
       MTL_PARAMETERS           MP,
       HR_ORGANIZATION_UNITS    HOUV,
       RA_SALESREP_TERRITORIES  RST,
       RA_SALESREPS_ALL         RSA,
       HZ_CUST_ACCOUNTS_ALL     HCA,
       HZ_CUST_ACCT_SITES_ALL   HCASA,
       HZ_CUST_SITE_USES_ALL    HCSUA,
       HZ_PARTIES               HP,        --8  
       HZ_LOCATIONS             HL,        --14 
       HZ_PARTY_SITES           HPS,       --9 
       HZ_CUST_PROFILE_AMTS     HCPA,
      (
        SELECT DISTINCT
               SITE_USE_ID, 
               SITE_USE_CODE,
               CUST_ACCT_SITE_ID  CODE
          FROM HZ_CUST_SITE_USES_ALL
         WHERE SITE_USE_CODE = 'BILL_TO' 
      ) BILL_TO,
      (
        SELECT HCSUA.SITE_USE_ID
              ,NVL(HCASA.GLOBAL_ATTRIBUTE12,0) CODE_42_PERCENTAGE
         FROM  HZ_CUST_ACCT_SITES_ALL   HCASA,
               HZ_CUST_SITE_USES_ALL    HCSUA
         WHERE HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
           AND HCSUA.SITE_USE_CODE     = 'BILL_TO'
      ) CODE_42,
      (
        SELECT SUBSTR(ATTRIBUTE4,1,2) REGN
              ,SUBSTR(NAME,1,3)       DEPO_CODE
              ,NAME                   DEPO_NAME
              ,ORGANIZATION_ID
          FROM HR_ALL_ORGANIZATION_UNITS
         WHERE ATTRIBUTE1 = 'DEPOT' 
       ) DEPO,
        FND_LOOKUP_VALUES   FLV 
WHERE  MP.ORGANIZATION_ID      = HOUV.ORGANIZATION_ID
AND    MP.ORGANIZATION_CODE    = RT.SEGMENT3 
AND    RT.TERRITORY_ID         = RST.TERRITORY_ID
AND    RST.SALESREP_ID         = RSA.SALESREP_ID
AND    HCA.CUST_ACCOUNT_ID     = HCASA.CUST_ACCOUNT_ID
AND    HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
AND    HCSUA.TERRITORY_ID      = RT.TERRITORY_ID
AND    HCA.STATUS = 'A'
AND    RST.END_DATE_ACTIVE IS NULL 
AND    HCSUA.SITE_USE_CODE       = 'SHIP_TO'
AND    HCSUA.BILL_TO_SITE_USE_ID = BILL_TO.SITE_USE_ID(+)
AND    HCSUA.BILL_TO_SITE_USE_ID = CODE_42.SITE_USE_ID(+)
AND    HCA.PARTY_ID              = HP.PARTY_ID               --OK     
AND    HCASA.PARTY_SITE_ID       = HPS.PARTY_SITE_ID         --OK 
AND    HPS.LOCATION_ID           = HL.LOCATION_ID            --OK   
AND    HCA.CUST_ACCOUNT_ID       = HCPA.CUST_ACCOUNT_ID(+)
AND    FLV.LOOKUP_CODE           = HCASA.GLOBAL_ATTRIBUTE10
AND    FLV.LOOKUP_TYPE           = 'BPIL_CUSTOMER_TYPE'
AND    DEPO.DEPO_CODE            = RT.SEGMENT3   
--AND    UPPER(HL.ADDRESS1) NOT LIKE '%DAMAGE%'
--AND HCA.ACCOUNT_NUMBER = 70936
ORDER BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18



