
  SELECT
  CUST_DTLS.CUST_ACC_NO CUST_ACC_NO,
  CUST_DTLS.CUST_NAME   CUST_NAME,
  CUST_DTLS.BILL_ID     BILL_ID,
  VOL_DTLS.TRX_DATE     TRX_DATE,
  VOL_DTLS.TRX_NUMBER   TRX_NUMBER,
  VOL_DTLS.SKU          SKU,
  VOL_DTLS.DESCRIPTION  DESCRIPTION,
  VOL_DTLS.DESCRIPTION1 DESCRIPTION1,
  VOL_DTLS.EXTENDED_AMOUNT EXTENDED_AMOUNT,
  VOL_DTLS.VOLUME_LIFTED
FROM
(SELECT
    HCA.ACCOUNT_NUMBER  CUST_ACC_NO,
    HCA.ACCOUNT_NAME     CUST_NAME,
    HCSUA.SITE_USE_ID    BILL_ID
FROM
         AR.HZ_CUST_ACCOUNTS         HCA,
         AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
         AR.HZ_CUST_SITE_USES_ALL  HCSUA,
         HR.HR_ALL_ORGANIZATION_UNITS  HAOU
WHERE
         HCA.CUST_ACCOUNT_ID=HCASA.CUST_ACCOUNT_ID
         AND  HCASA.CUST_ACCT_SITE_ID=HCSUA.CUST_ACCT_SITE_ID
         AND  HCSUA.WAREHOUSE_ID=HAOU.ORGANIZATION_ID
         AND  HCSUA.SITE_USE_CODE='BILL_TO'
         AND  HAOU.ATTRIBUTE1='DEPOT') CUST_DTLS,
(SELECT AAA. TRX_NUMBER,
       AAA.TRX_DATE TRX_DATE,
       BBB. SKU     SKU,
       BBB.DESCRIPTION   DESCRIPTION,
       AAA.VOLUME_LIFTED VOLUME_LIFTED,
       AAA.BILL_ID       BILL_ID,
       AAA.DESCRIPTION1  DESCRIPTION1,
       AAA. EXTENDED_AMOUNT EXTENDED_AMOUNT

FROM
(SELECT  RCTLA.INVENTORY_ITEM_ID    INV_ID, 
         RCTA.TRX_NUMBER                 TRX_NUMBER,
         RCTA.TRX_DATE                   TRX_DATE,
         RCTLA.QUANTITY_INVOICED         VOLUME_LIFTED,
         RCTA.BILL_TO_SITE_USE_ID        BILL_ID,
         RCTLA.DESCRIPTION               DESCRIPTION1,
         RCTLA.EXTENDED_AMOUNT           EXTENDED_AMOUNT
         
FROM     AR.RA_CUSTOMER_TRX_LINES_ALL    RCTLA,
         AR.RA_CUSTOMER_TRX_ALL          RCTA,
         AR.RA_CUST_TRX_TYPES_ALL        RCTTA
WHERE    RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID
         AND RCTA.CUST_TRX_TYPE_ID=RCTTA.CUST_TRX_TYPE_ID
         AND RCTTA.TYPE='INV')  AAA,
(SELECT MSIB.INVENTORY_ITEM_ID    INV_ID,
        MSIB.SEGMENT1             SKU,
        MSIB.DESCRIPTION          DESCRIPTION
        FROM 
        INV.MTL_SYSTEM_ITEMS_B          MSIB
        WHERE MSIB.ORGANIZATION_ID=83)   BBB
  WHERE AAA.INV_ID=BBB.INV_ID)   VOL_DTLS
  WHERE CUST_DTLS.BILL_ID=VOL_DTLS.BILL_ID;