SELECT
SUBSTR(HAOU.ATTRIBUTE4,1,2)             REGN,
SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)-1) DEPO_NAME,
TO_NUMBER(RT.SEGMENT4)                  TRE_CODE,
HCA.ACCOUNT_NUMBER                      ACC_NO,
HCSUA.SITE_USE_ID                       BILL_TO,
HCA.ACCOUNT_NAME                        ACC_NAME
FROM
 AR.HZ_CUST_ACCOUNTS         HCA,
         AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
         AR.HZ_CUST_SITE_USES_ALL  HCSUA,
         HR.HR_ALL_ORGANIZATION_UNITS  HAOU,
         AR.RA_TERRITORIES             RT
WHERE
         HCA.CUST_ACCOUNT_ID=HCASA.CUST_ACCOUNT_ID
         AND  HCASA.CUST_ACCT_SITE_ID=HCSUA.CUST_ACCT_SITE_ID
         AND  HCSUA.WAREHOUSE_ID=HAOU.ORGANIZATION_ID
         AND HCSUA.TERRITORY_ID       = RT.TERRITORY_ID
         AND  HCSUA.SITE_USE_CODE='BILL_TO'
         AND  HAOU.ATTRIBUTE1='DEPOT'