SELECT DEPO.REGN  REGION,
       DEPO.DEPO_NAME  DEPO_NAME,
       CUST_DTLS.CUST_ACCT_NO,
       CUST_DTLS.S_ID
FROM
(SELECT 
        HCA.ACCOUNT_NUMBER          CUST_ACCT_NO,
        HCA.ACCOUNT_NAME            CUST_ACCT_NAME,
        HCSUA.BILL_TO_SITE_USE_ID   CUST_BILL_ID,
        HCSUA.WAREHOUSE_ID          WID,
        HCSUA.SITE_USE_ID           S_ID
FROM 
        AR.HZ_CUST_ACCOUNTS         HCA,
        AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
        AR.HZ_CUST_SITE_USES_ALL   HCSUA
WHERE  
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
    AND HCSUA.SITE_USE_CODE='BILL_TO') CUST_DTLS,
    
(SELECT SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)) DEPO_NAME,
        SUBSTR(HAOU.ATTRIBUTE4,4,LENGTH(HAOU.ATTRIBUTE4)) REGN,
        HAOU.ORGANIZATION_ID     ORGID
 FROM HR.HR_ALL_ORGANIZATION_UNITS HAOU
 WHERE HAOU.ATTRIBUTE1='DEPOT') DEPO
 WHERE CUST_DTLS.WID=DEPO.ORGID;
 