SELECT CUST_DTLS.REGION REGION,
       CUST_DTLS.DEPO_NAME  DEPO_NAME,
       CUST_DTLS.ACC_NO ACC_NO,
       CUST_DTLS.BILL_TO,
       SKU_DTLS.SKU  SKU,
       SKU_DTLS.DESCRIPTION DESCRIPTION,
       SKU_DTLS.VOLUME VOLUME
 FROM
     (SELECT SKU_DTLS.SKU   SKU,
       CUST_DES.VOLUME   VOLUME,
       CUST_DES.DESCRIPTION   DESCRIPTION,
       CUST_DES.BILL_ID       BILL_ID
       FROM
         (SELECT 
            DISTINCT(MSIB.INVENTORY_ITEM_ID )  IID,
             MSIB.SEGMENT1    SKU
             FROM inv.mtl_system_items_b          MSIB) SKU_DTLS,
    
    (SELECT
     RCTLA.QUANTITY_INVOICED     VOLUME,
     RCTLA.DESCRIPTION           DESCRIPTION,
     RCTLA.INVENTORY_ITEM_ID     IID,
     RCTA.BILL_TO_SITE_USE_ID    BILL_ID
     FROM
   ar.ra_customer_trx_lines_all    RCTLA,
   AR.RA_CUSTOMER_TRX_ALL          RCTA
   WHERE 
   RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID) CUST_DES
   WHERE SKU_DTLS.IID=CUST_DES.IID)                             SKU_DTLS,
       (SELECT DEPO.REGN  REGION,
       DEPO.DEPO_NAME  DEPO_NAME,
       CUST_DTLS.CUST_ACCT_NO   ACC_NO,
       CUST_DTLS.S_ID   BILL_TO,
       CUST_DTLS.BILL_ID   BILL_ID
        FROM
        (SELECT 
        HCA.ACCOUNT_NUMBER          CUST_ACCT_NO,
        HCA.ACCOUNT_NAME            CUST_ACCT_NAME,
        HCSUA.BILL_TO_SITE_USE_ID   CUST_BILL_ID,
        HCSUA.WAREHOUSE_ID          WID,
        HCSUA.SITE_USE_ID           S_ID,
        HCSUA.BILL_TO_SITE_USE_ID   BILL_ID
        FROM 
        AR.HZ_CUST_ACCOUNTS         HCA,
        AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
        AR.HZ_CUST_SITE_USES_ALL   HCSUA
         WHERE  
           HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
           AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID) CUST_DTLS,
       (SELECT SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)) DEPO_NAME,
        SUBSTR(HAOU.ATTRIBUTE4,4,LENGTH(HAOU.ATTRIBUTE4)) REGN,
        HAOU.ORGANIZATION_ID     ORGID
 FROM HR.HR_ALL_ORGANIZATION_UNITS HAOU
 WHERE HAOU.ATTRIBUTE1='DEPOT') DEPO
 WHERE CUST_DTLS.WID=DEPO.ORGID)                                CUST_DTLS
 WHERE CUST_DTLS.BILL_ID=SKU_DTLS.BILL_ID;