inv.mtl_system_items_b          
ar.ra_customer_trx_lines_all
AR.RA_CUSTOMER_TRX_ALL    
AR.HZ_CUST_SITE_USES_ALL 
HR.HR_ALL_ORGANIZATION_UNITS 
AR.HZ_CUST_ACCOUNTS         HCA


SELECT 
  HCSUA.SITE_USE_ID,
  RCTA.CUSTOMER_TRX_ID
FROM
AR.RA_CUSTOMER_TRX_ALL     RCTA,
AR.HZ_CUST_SITE_USES_ALL   HCSUA
WHERE HCSUA.BILL_TO_SITE_USE_ID=RCTA.BILL_TO_SITE_USE_ID;