SELECT 
        HCA.ACCOUNT_NUMBER          CUST_ACCT_NO,
        HCSUA.SITE_USE_ID           S_ID
        FROM 
        AR.HZ_CUST_ACCOUNTS         HCA,
        AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
        AR.HZ_CUST_SITE_USES_ALL   HCSUA
WHERE  
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID;