SELECT
DISTINCT(VOL_DTLS.INVOICE_ID)  INVOICE_ID,
SKU_DTLS.SKU   SKU,
SKU_DTLS. DESCRIPTION   DESCRIPTION,
VOL_DTLS.VOLUME_LIFTED  VOLUME_LIFTED,
VOL_DTLS.BILL_ID
FROM
  (SELECT
   RCTA.CUSTOMER_TRX_ID  INVOICE_ID,
  RCTLA.QUANTITY_INVOICED  VOLUME_LIFTED,
  RCTLA.INVENTORY_ITEM_ID   INV_ID,
  RCTA.BILL_TO_SITE_USE_ID  BILL_ID
FROM 
ar.ra_customer_trx_lines_all RCTLA,
AR.RA_CUSTOMER_TRX_ALL  RCTA
WHERE  RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID) VOL_DTLS,
(SELECT 
  DISTINCT(MSIB.INVENTORY_ITEM_ID) INV_ID,
  MSIB.SEGMENT1    SKU,
  MSIB.DESCRIPTION  DESCRIPTION
FROM
inv.mtl_system_items_b       MSIB) SKU_DTLS
WHERE VOL_DTLS.INV_ID=SKU_DTLS.INV_ID;