SELECT
HCA.CUST_ACCOUNT_ID CUST_ACC_NO,
HCA.ACCOUNT_NAME    CUST_NAME,
GHI.BILL_TO          BILL_TO,
GHI.INVOICE_ID      INVOICE_ID,
GHI.SKU             SKU,
GHI.DESCRIPTION     DESCRIPTION,
GHI.VOLUME_LIFTED   VOLUME_LIFTED,
GHI.WID             WID
FROM
AR.HZ_CUST_ACCOUNTS         HCA,
AR.HZ_CUST_ACCT_SITES_ALL   HCASA,
(SELECT 
HCSUA.SITE_USE_ID  BILL_TO,
HCSUA.CUST_ACCT_SITE_ID CID,
HCSUA.WAREHOUSE_ID      WID,
ABC.INVOICE_ID     INVOICE_ID,
ABC.SKU            SKU,
ABC.DESCRIPTION    DESCRIPTION,
ABC.VOLUME_LIFTED  VOLUME_LIFTED
FROM
AR.HZ_CUST_SITE_USES_ALL  HCSUA,
(SELECT
DISTINCT(VOL_DTLS.INVOICE_ID)  INVOICE_ID,
SKU_DTLS.SKU   SKU,
SKU_DTLS. DESCRIPTION   DESCRIPTION,
VOL_DTLS.VOLUME_LIFTED  VOLUME_LIFTED,
VOL_DTLS.BILL_ID
FROM
  (SELECT
   RCTA.CUSTOMER_TRX_ID  INVOICE_ID,
  RCTLA.QUANTITY_INVOICED  VOLUME_LIFTED,
  RCTLA.INVENTORY_ITEM_ID   INV_ID,
  RCTA.BILL_TO_SITE_USE_ID  BILL_ID
FROM 
ar.ra_customer_trx_lines_all RCTLA,
AR.RA_CUSTOMER_TRX_ALL  RCTA
WHERE  RCTA.CUSTOMER_TRX_ID=RCTLA.CUSTOMER_TRX_ID) VOL_DTLS,
(SELECT 
  DISTINCT(MSIB.INVENTORY_ITEM_ID) INV_ID,
  MSIB.SEGMENT1    SKU,
  MSIB.DESCRIPTION  DESCRIPTION
FROM
inv.mtl_system_items_b       MSIB) SKU_DTLS
WHERE VOL_DTLS.INV_ID=SKU_DTLS.INV_ID) ABC
WHERE
ABC.BILL_ID=HCSUA.BILL_TO_SITE_USE_ID) GHI
WHERE
HCA.CUST_ACCOUNT_ID=HCASA.CUST_ACCOUNT_ID
AND HCASA.CUST_ACCT_SITE_ID=GHI.CID;