SELECT
        CUST_DTLS.CUST_AID,
        DEPO_DTLS.REGION,
        DEPO_DTLS.DEPO_CODE,
        DEPO_DTLS.DEPO_NAME,
        CUST_DTLS.CUST_ANO,
        CUST_DTLS.CUST_ANM,
        CUST_DTLS.BILL_TO,
        --DEPO_DTLS.ORGANIZATION_ID,
        --RT_DTLS.RT_NAME,
        VOL_DTLS.QUANTITY_INVOICED
FROM
(SELECT
        HCA.CUST_ACCOUNT_ID  CUST_AID,
        HCA.ACCOUNT_NUMBER   CUST_ANO,
        HCA.ACCOUNT_NAME     CUST_ANM,
        HCSUA.WAREHOUSE_ID   WID,
        HCSUA.TERRITORY_ID   TER_ID,
        HCSUA.BILL_TO_SITE_USE_ID   BILL_ID,
        HCSUA.SITE_USE_ID         BILL_TO
FROM 
        AR.HZ_CUST_ACCOUNTS            HCA,
        AR.HZ_CUST_ACCT_SITES_ALL      HCASA,
        AR.HZ_CUST_SITE_USES_ALL       HCSUA
WHERE
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
    AND HCSUA.SITE_USE_CODE = 'BILL_TO'
 ) CUST_DTLS,
(SELECT
        SUBSTR(HAOU.NAME,1,3)  DEPO_CODE,
        SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)-1) DEPO_NAME,
        NVL(SUBSTR(HAOU.ATTRIBUTE4,4,LENGTH(HAOU.ATTRIBUTE4)),'NULL')  REGION,
        HAOU.ORGANIZATION_ID                                           ORGANIZATION_ID
FROM  HR.HR_ALL_ORGANIZATION_UNITS  HAOU  
WHERE ATTRIBUTE1 = 'DEPOT'
) DEPO_DTLS,
(SELECT
        RT.TERRITORY_ID  RT_ID,
        RT.NAME          RT_NAME
FROM 
    AR.RA_TERRITORIES RT
) RT_DTLS,

(
SELECT
        RCTLA.QUANTITY_INVOICED,
        RCTA.BILL_TO_SITE_USE_ID    BILL_ID 
FROM 
        AR.RA_CUSTOMER_TRX_ALL       RCTA,
        AR.RA_CUSTOMER_TRX_LINES_ALL RCTLA,
        AR.RA_CUST_TRX_TYPES_ALL     RCTTA
WHERE
        RCTA.CUSTOMER_TRX_ID = RCTLA.CUSTOMER_TRX_ID
    AND RCTA.CUST_TRX_TYPE_ID =RCTTA.CUST_TRX_TYPE_ID
) VOL_DTLS

WHERE
        CUST_DTLS.WID = DEPO_DTLS.ORGANIZATION_ID
    AND CUST_DTLS.TER_ID = RT_DTLS.RT_ID
    AND VOL_DTLS.BILL_ID = CUST_DTLS.BILL_ID;
       