--AR.HZ_CUST_ACCOUNTS                        HCA 
--AR.HZ_CUST_ACCT_SITES_ALL                  HCASA 
--AR.HZ_CUST_SITE_USES_ALL                   HCSUA 
--HR.HR_ALL_ORGANIZATION_UNITS               HAOU 
(SELECT
        HCA.CUST_ACCOUNT_ID  CUST_ACC_ID,
        HCA.ACCOUNT_NUMBER   CUST_ACC_NO,
        HCA.ACCOUNT_NAME     CUST_ACC_NM,
        HCSUA.WAREHOUSE_ID   W_HSE_ID,
        NVL(HCSUA.TERRITORY_ID,0)   TER_ID
FROM 
        AR.HZ_CUST_ACCOUNTS            HCA,
        AR.HZ_CUST_ACCT_SITES_ALL      HCASA,
        AR.HZ_CUST_SITE_USES_ALL       HCSUA
WHERE
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID)  CUST_DTLS,

(SELECT
        SUBSTR(HAOU.ATTRIBUTE4,1,2)     REGION,
        SUBSTR(HAOU.NAME,1,3)           DPO_CODE,
        SUBSTR(HAOU.NAME,5)             DPO_NAME
FROM
        HR.HR_ALL_ORGANIZATION_UNITS   HAOU
WHERE
        HAOU.ATTRIBUTE1 = 'DEPOT'
    AND HAOU.ATTRIBUTE4 IS NOT NULL  
ORDER BY 1;      
)    
    