select to_date('22-03-2014','dd-mm-yyyy') from dual;

SELECT 
HAOU.ORGANIZATION_ID OID,
SUBSTR(HAOU.ATTRIBUTE4,4,LENGTH(ATTRIBUTE4))
FROM HR.HR_ALL_ORGANIZATION_UNITS HAOU
WHERE HAOU.ATTRIBUTE4 IS NULL
OR HAOU.ATTRIBUTE4 IS NOT NULL;
SELECT COUNT(*) FROM HR.HR_ALL_ORGANIZATION_UNITS;

SELECT 
       DEPO_DTLS.DEPO_CODE,
       DEPO_DTLS.DEPO_NAME,
       COUNT(CUST_DTLS.CUST_AID) TOTAL_NO_CUSTOMER
       FROM
(SELECT
        HCA.CUST_ACCOUNT_ID  CUST_AID,
        HCA.ACCOUNT_NUMBER   CUST_ANO,
        HCA.ACCOUNT_NAME     CUST_ANM,
        HCSUA.WAREHOUSE_ID   WID,
        HCSUA.TERRITORY_ID   TER_ID
FROM 
        AR.HZ_CUST_ACCOUNTS            HCA,
        AR.HZ_CUST_ACCT_SITES_ALL      HCASA,
        AR.HZ_CUST_SITE_USES_ALL       HCSUA
WHERE
        HCA.CUST_ACCOUNT_ID = HCASA.CUST_ACCOUNT_ID
    AND HCASA.CUST_ACCT_SITE_ID = HCSUA.CUST_ACCT_SITE_ID
)CUST_DTLS, 
(SELECT
        SUBSTR(HAOU.NAME,1,3)  DEPO_CODE,
        SUBSTR(HAOU.NAME,5,LENGTH(HAOU.NAME)-1) DEPO_NAME,
        NVL(SUBSTR(HAOU.ATTRIBUTE4,4,LENGTH(HAOU.ATTRIBUTE4)),'NULL')  REGION,
        HAOU.ORGANIZATION_ID                                           ORGANIZATION_ID
FROM  HR.HR_ALL_ORGANIZATION_UNITS  HAOU  
WHERE ATTRIBUTE1 = 'DEPOT'
)DEPO_DTLS
WHERE 
     CUST_DTLS.WID=DEPO_DTLS.ORGANIZATION_ID
     GROUP BY DEPO_DTLS.DEPO_CODE,DEPO_DTLS.DEPO_NAME;
